using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MTIPC.MQL
{
    public enum TICK_FLAG : uint
    {
        TICK_FLAG_BID,
        TICK_FLAG_ASK,
        TICK_FLAG_LAST,
        TICK_FLAG_VOLUME,
        TICK_FLAG_BUY,
        TICK_FLAG_SELL,
    }

    public enum ENUM_BOOK_TYPE : int
    {
        BOOK_TYPE_SELL,
        BOOK_TYPE_BUY,
        BOOK_TYPE_SELL_MARKET,
        BOOK_TYPE_BUY_MARKET
    }

    public enum ENUM_SYMBOL_SECTOR : int
    {
        SECTOR_UNDEFINED,
        SECTOR_BASIC_MATERIALS,
        SECTOR_COMMUNICATION_SERVICES,
        SECTOR_CONSUMER_CYCLICAL,
        SECTOR_CONSUMER_DEFENSIVE,
        SECTOR_CURRENCY,
        SECTOR_CURRENCY_CRYPTO,
        SECTOR_ENERGY,
        SECTOR_FINANCIAL,
        SECTOR_HEALTHCARE,
        SECTOR_INDUSTRIALS,
        SECTOR_REAL_ESTATE,
        SECTOR_TECHNOLOGY,
        SECTOR_UTILITIES,
    }

    public enum ENUM_SYMBOL_INDUSTRY : int
    {
        INDUSTRY_UNDEFINED,
        INDUSTRY_AGRICULTURAL_INPUTS,
        INDUSTRY_ALUMINIUM,
        INDUSTRY_BUILDING_MATERIALS,
        INDUSTRY_CHEMICALS,
        INDUSTRY_COKING_COAL,
        INDUSTRY_COPPER,
        INDUSTRY_GOLD,
        INDUSTRY_LUMBER_WOOD,
        INDUSTRY_INDUSTRIAL_METALS,
        INDUSTRY_PRECIOUS_METALS,
        INDUSTRY_PAPER,
        INDUSTRY_SILVER,
        INDUSTRY_SPECIALTY_CHEMICALS,
        INDUSTRY_STEEL,
        INDUSTRY_ADVERTISIN,
        INDUSTRY_BROADCASTING,
        INDUSTRY_GAMING_MULTIMEDIA,
        INDUSTRY_ENTERTAINMENT,
        INDUSTRY_INTERNET_CONTENT,
        INDUSTRY_PUBLISHING,
        INDUSTRY_TELECOM,
        INDUSTRY_APPAREL_MANUFACTURING,
        INDUSTRY_APPAREL_RETAIL,
        INDUSTRY_AUTO_MANUFACTURERS,
        INDUSTRY_AUTO_PARTS,
        INDUSTRY_AUTO_DEALERSHIP,
        INDUSTRY_DEPARTMENT_STORES,
        INDUSTRY_FOOTWEAR_ACCESSORIES,
        INDUSTRY_FURNISHINGS,
        INDUSTRY_GAMBLING,
        INDUSTRY_HOME_IMPROV_RETAIL,
        INDUSTRY_INTERNET_RETAIL,
        INDUSTRY_LEISURE,
        INDUSTRY_LODGING,
        INDUSTRY_LUXURY_GOODS,
        INDUSTRY_PACKAGING_CONTAINERS,
        INDUSTRY_PERSONAL_SERVICES,
        INDUSTRY_RECREATIONAL_VEHICLES,
        INDUSTRY_RESIDENT_CONSTRUCTION,
        INDUSTRY_RESORTS_CASINOS,
        INDUSTRY_RESTAURANTS,
        INDUSTRY_SPECIALTY_RETAIL,
        INDUSTRY_TEXTILE_MANUFACTURING,
        INDUSTRY_TRAVEL_SERVICES,
        INDUSTRY_BEVERAGES_BREWERS,
        INDUSTRY_BEVERAGES_NON_ALCO,
        INDUSTRY_BEVERAGES_WINERIES,
        INDUSTRY_CONFECTIONERS,
        INDUSTRY_DISCOUNT_STORES,
        INDUSTRY_EDUCATION_TRAINIG,
        INDUSTRY_FARM_PRODUCTS,
        INDUSTRY_FOOD_DISTRIBUTION,
        INDUSTRY_GROCERY_STORES,
        INDUSTRY_HOUSEHOLD_PRODUCTS,
        INDUSTRY_PACKAGED_FOODS,
        INDUSTRY_TOBACCO,
        INDUSTRY_OIL_GAS_DRILLING,
        INDUSTRY_OIL_GAS_EP,
        INDUSTRY_OIL_GAS_EQUIPMENT,
        INDUSTRY_OIL_GAS_INTEGRATED,
        INDUSTRY_OIL_GAS_MIDSTREAM,
        INDUSTRY_OIL_GAS_REFINING,
        INDUSTRY_THERMAL_COAL,
        INDUSTRY_URANIUM,
        INDUSTRY_EXCHANGE_TRADED_FUND,
        INDUSTRY_ASSETS_MANAGEMENT,
        INDUSTRY_BANKS_DIVERSIFIED,
        INDUSTRY_BANKS_REGIONAL,
        INDUSTRY_CAPITAL_MARKETS,
        INDUSTRY_CLOSE_END_FUND_DEBT,
        INDUSTRY_CLOSE_END_FUND_EQUITY,
        INDUSTRY_CLOSE_END_FUND_FOREIGN,
        INDUSTRY_CREDIT_SERVICES,
        INDUSTRY_FINANCIAL_CONGLOMERATE,
        INDUSTRY_FINANCIAL_DATA_EXCHANGE,
        INDUSTRY_INSURANCE_BROKERS,
        INDUSTRY_INSURANCE_DIVERSIFIED,
        INDUSTRY_INSURANCE_LIFE,
        INDUSTRY_INSURANCE_PROPERTY,
        INDUSTRY_INSURANCE_REINSURANCE,
        INDUSTRY_INSURANCE_SPECIALTY,
        INDUSTRY_MORTGAGE_FINANCE,
        INDUSTRY_SHELL_COMPANIES,
        INDUSTRY_BIOTECHNOLOGY,
        INDUSTRY_DIAGNOSTICS_RESEARCH,
        INDUSTRY_DRUGS_MANUFACTURERS,
        INDUSTRY_DRUGS_MANUFACTURERS_SPEC,
        INDUSTRY_HEALTHCARE_PLANS,
        INDUSTRY_HEALTH_INFORMATION,
        INDUSTRY_MEDICAL_FACILITIES,
        INDUSTRY_MEDICAL_DEVICES,
        INDUSTRY_MEDICAL_DISTRIBUTION,
        INDUSTRY_MEDICAL_INSTRUMENTS,
        INDUSTRY_PHARM_RETAILERS,
        INDUSTRY_AEROSPACE_DEFENSE,
        INDUSTRY_AIRLINES,
        INDUSTRY_AIRPORTS_SERVICES,
        INDUSTRY_BUILDING_PRODUCTS,
        INDUSTRY_BUSINESS_EQUIPMENT,
        INDUSTRY_CONGLOMERATES,
        INDUSTRY_CONSULTING_SERVICES,
        INDUSTRY_ELECTRICAL_EQUIPMENT,
        INDUSTRY_ENGINEERING_CONSTRUCTION,
        INDUSTRY_FARM_HEAVY_MACHINERY,
        INDUSTRY_INDUSTRIAL_DISTRIBUTION,
        INDUSTRY_INFRASTRUCTURE_OPERATIONS,
        INDUSTRY_FREIGHT_LOGISTICS,
        INDUSTRY_MARINE_SHIPPING,
        INDUSTRY_METAL_FABRICATION,
        INDUSTRY_POLLUTION_CONTROL,
        INDUSTRY_RAILROADS,
        INDUSTRY_RENTAL_LEASING,
        INDUSTRY_SECURITY_PROTECTION,
        INDUSTRY_SPEALITY_BUSINESS_SERVICES,
        INDUSTRY_SPEALITY_MACHINERY,
        INDUSTRY_STUFFING_EMPLOYMENT,
        INDUSTRY_TOOLS_ACCESSORIES,
        INDUSTRY_TRUCKING,
        INDUSTRY_WASTE_MANAGEMENT,
        INDUSTRY_REAL_ESTATE_DEVELOPMENT,
        INDUSTRY_REAL_ESTATE_DIVERSIFIED,
        INDUSTRY_REAL_ESTATE_SERVICES,
        INDUSTRY_REIT_DIVERSIFIED,
        INDUSTRY_REIT_HEALTCARE,
        INDUSTRY_REIT_HOTEL_MOTEL,
        INDUSTRY_REIT_INDUSTRIAL,
        INDUSTRY_REIT_MORTAGE,
        INDUSTRY_REIT_OFFICE,
        INDUSTRY_REIT_RESIDENTAL,
        INDUSTRY_REIT_RETAIL,
        INDUSTRY_REIT_SPECIALITY,
        INDUSTRY_COMMUNICATION_EQUIPMENT,
        INDUSTRY_COMPUTER_HARDWARE,
        INDUSTRY_CONSUMER_ELECTRONICS,
        INDUSTRY_ELECTRONIC_COMPONENTS,
        INDUSTRY_ELECTRONIC_DISTRIBUTION,
        INDUSTRY_IT_SERVICES,
        INDUSTRY_SCIENTIFIC_INSTRUMENTS,
        INDUSTRY_SEMICONDUCTOR_EQUIPMENT,
        INDUSTRY_SEMICONDUCTORS,
        INDUSTRY_SOFTWARE_APPLICATION,
        INDUSTRY_SOFTWARE_INFRASTRUCTURE,
        INDUSTRY_SOLAR,
        INDUSTRY_UTILITIES_DIVERSIFIED,
        INDUSTRY_UTILITIES_POWERPRODUCERS,
        INDUSTRY_UTILITIES_RENEWABLE,
        INDUSTRY_UTILITIES_REGULATED_ELECTRIC,
        INDUSTRY_UTILITIES_REGULATED_GAS,
        INDUSTRY_UTILITIES_REGULATED_WATER,
        INDUSTRY_UTILITIES_FIRST,
        INDUSTRY_UTILITIES_LAST,
    }

    public enum ENUM_SYMBOL_CHART_MODE : int
    {
        SYMBOL_CHART_MODE_BID,
        SYMBOL_CHART_MODE_LAST
    }

    public enum ENUM_SYMBOL_CALC_MODE : int
    {
        SYMBOL_CALC_MODE_FOREX,
        SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE,
        SYMBOL_CALC_MODE_FUTURES,
        SYMBOL_CALC_MODE_CFD,
        SYMBOL_CALC_MODE_CFDINDEX,
        SYMBOL_CALC_MODE_CFDLEVERAGE,
        SYMBOL_CALC_MODE_EXCH_STOCKS,
        SYMBOL_CALC_MODE_EXCH_FUTURES,
        SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS,
        SYMBOL_CALC_MODE_EXCH_BONDS,
        SYMBOL_CALC_MODE_EXCH_STOCKS_MOEX,
        SYMBOL_CALC_MODE_EXCH_BONDS_MOEX,
        SYMBOL_CALC_MODE_SERV_COLLATERAL
    }

    public enum ENUM_SYMBOL_TRADE_MODE : int
    {
        SYMBOL_TRADE_MODE_DISABLED,
        SYMBOL_TRADE_MODE_LONGONLY,
        SYMBOL_TRADE_MODE_SHORTONLY,
        SYMBOL_TRADE_MODE_CLOSEONLY,
        SYMBOL_TRADE_MODE_FULL
    }

    public enum ENUM_SYMBOL_TRADE_EXECUTION : int
    {
        SYMBOL_TRADE_EXECUTION_REQUEST,
        SYMBOL_TRADE_EXECUTION_INSTANT,
        SYMBOL_TRADE_EXECUTION_MARKET,
        SYMBOL_TRADE_EXECUTION_EXCHANGE
    }

    public enum ENUM_SYMBOL_SWAP_MODE : int
    {
        SYMBOL_SWAP_MODE_DISABLED,
        SYMBOL_SWAP_MODE_POINTS,
        SYMBOL_SWAP_MODE_CURRENCY_SYMBOL,
        SYMBOL_SWAP_MODE_CURRENCY_MARGIN,
        SYMBOL_SWAP_MODE_CURRENCY_DEPOSIT,
        SYMBOL_SWAP_MODE_INTEREST_CURRENT,
        SYMBOL_SWAP_MODE_INTEREST_OPEN,
        SYMBOL_SWAP_MODE_REOPEN_CURRENT,
        SYMBOL_SWAP_MODE_REOPEN_BID
    }

    public enum ENUM_DAY_OF_WEEK : int
    {
        SUNDAY,
        MONDAY,
        TUESDAY,
        WEDNESDAY,
        THURSDAY,
        FRIDAY,
        SATURDAY
    }

    public enum ENUM_SYMBOL_OPTION_MODE : int
    {
        SYMBOL_OPTION_MODE_EUROPEAN,
        SYMBOL_OPTION_MODE_AMERICAN
    }

    public enum ENUM_SYMBOL_OPTION_RIGHT : int
    {
        SYMBOL_OPTION_RIGHT_CALL,
        SYMBOL_OPTION_RIGHT_PUT,
    }

    public enum ENUM_SYMBOL_ORDER_TYPE : int 
    { 
        SYMBOL_ORDER_MARKET,
        SYMBOL_ORDER_LIMIT,
        SYMBOL_ORDER_STOP,
        SYMBOL_ORDER_STOP_LIMIT,
        SYMBOL_ORDER_SL,
        SYMBOL_ORDER_TP,
        SYMBOL_ORDER_CLOSEBY
    }

    public enum ENUM_ORDER_TYPE_FILLING : int
    {
        SYMBOL_TRADE_EXECUTION_INSTANT,
        SYMBOL_TRADE_EXECUTION_REQUEST,
        SYMBOL_TRADE_EXECUTION_MARKET,
        SYMBOL_TRADE_EXECUTION_EXCHANGE,
    }

    public enum ENUM_SYMBOL_ORDER_GTC_MODE : int
    {
        SYMBOL_ORDERS_GTC,
        SYMBOL_ORDERS_DAILY,
        SYMBOL_ORDERS_DAILY_EXCLUDING_STOPS
    }

    public enum TIMEFRAME
    {
        M1 = 1,
        M2 = 2,
        M3 = 3,
        M4 = 4,
        M5 = 5,
        M6 = 6,
        M10 = 10,
        M12 = 12,
        M15 = 15,
        M20 = 20,
        M30 = 30,
        H1 = 16385,
        H2 = 16386,
        H3 = 16387,
        H4 = 16388,
        H6 = 16390,
        H8 = 16392,
        H12 = 16396,
        D1 = 16408,
        W1 = 32769,
        MN1 = 49152
    }

    public enum ENUM_POSITION_REASON : int
    {
        POSITION_REASON_CLIENT,
        POSITION_REASON_MOBILE,
        POSITION_REASON_WEB,
        POSITION_REASON_EXPERT
    }

    public enum ENUM_POSITION_TYPE : int
    {
        POSITION_TYPE_BUY,
        POSITION_TYPE_SELL
    }

    public enum ENUM_TRADE_REQUEST_ACTIONS : int
    {
        TRADE_ACTION_DEAL,
        TRADE_ACTION_PENDING,
        TRADE_ACTION_SLTP,
        TRADE_ACTION_MODIFY,
        TRADE_ACTION_REMOVE,
        TRADE_ACTION_CLOSE_BY
    }

}
